### PR TITLE
Material

### PR DESCRIPTION
**Pull request by mcer12**
Light web gui recoded in material design + added RGB multiplier values

### CODE REVIEW

**Comment by ghost** [comment]
This looks like a great improvement! Marius, I think your the best to review this. I have had a quick look over it and it looks good, but you're the expert!

**Comment by ghost** [comment]
Just noticed something @mcer12 that may be an issue. You use a CDN for some of the JS scripts required. This means if the user is running this offline for whatever reason, the UI won't work. Is there a fall back for this?

**Comment by mcer12** [comment]
CDN is used in original firmware also, no change there. This can't be avoided, only possibility I see is add notice for user to enable internet connection or do you have different idea?

**Comment by mariusmotea** [comment]
Hi Martin,

`#define light_version "1.0m"` need to be integer because is used to compare the current version with remote available version. Can you put 2.02?

**Comment by mcer12** [comment]
I think it would be best to replace it with 3.xx for material, I changed it in my last commit. Also added WS2812 generic sketch. I don't know if this pull request catches the changes or I have to make another pull request.

**Comment by mariusmotea** [comment]
3.0 is ok also. PR Must automatically be updated on every commit from your fork.

**Comment by mariusmotea** [comment]
@mcer12 can this be merged?

**Comment by mcer12** [comment]
I don't see why not. I have still some changes to make like choosing RGB/GRB/BRG mode in web admin but I will make a separate PR for it.

**Pull request merged**
