### PR TITLE
add ESP32_SK9822_FastLED_Strip sketch

### PR DESCRIPTION
**Pull request by linuzer**
Based on several other examples.
The sketch uses native FastLED, including their dimming functions.
Redesigned the code for better readability.
Separated the communication part with diyHue into an extra class.

### CODE REVIEW

**Comment by Jorgen-VikingGod** [comment]
you have to adapt the travis script to compile esp32 for your sketch instead of esp8266. Also some additional libraries you are using, needs to add.

Good example ofhow to create a travis script to address both (esp32 and esp8266) could be this one:
https://github.com/256dpi/arduino-mqtt/blob/master/.travis.yml

**Comment by mariusmotea** [comment]
I think you need to remote it from .env as Travis try to compile it using esp8266 board.
```
arduino-cli compile --fqbn esp8266:esp8266:nodemcu ${TRAVIS_BUILD_DIR}/Arduino/$SKETCH/$SKETCH.ino --output ${TRAVIS_BUILD_DIR}/Arduino/bin/$SKETCH.bin" exited with 1.
```

**Comment by linuzer** [comment]
Well, to be honest, I have no idea of Travis and how it works. I think I am unable to change the scripts the the way it would be necessary.
Can anybody please help me with this?

**Comment by mariusmotea** [comment]
I will fix it after merge. Thanks

**Comment by linuzer** [comment]
Thank you very much!

**Pull request merged**
