### PR TITLE
ArduinoJson migration from version 5.13.4 to 6.9.1

### PR DESCRIPTION
**Pull request by okanskose**

### CODE REVIEW

**Comment by mariusmotea** [comment]
Hi, thanks for this PR, it was something that i plan but i did not find time for it. There is a Travis compe build, i will try to understand where is the compile problem.

**Comment by ghost** [comment]
Here is your error:
```
/home/travis/build/diyhue/Lights/Arduino/Generic_RGB_CCT_Light/Generic_RGB_CCT_Light.ino: In function 'void restoreState()':
/home/travis/build/diyhue/Lights/Arduino/Generic_RGB_CCT_Light/Generic_RGB_CCT_Light.ino:302:12: error: 'class ArduinoJson691_000::DynamicJsonDocument' has no member named 'containsKey'
   if (json.containsKey("xy")) {
```
It looks like the `containsKey` function doesn't exist in the new version. I assume its been replaced with something else.

**Comment by okankoese** [comment]
Thanks, i will fix that.
Actually I compiled everything in order to test the build, but it might be that I missed that one!

**Comment by okanskose** [comment]
Thanks, it might be that I missed that one! I'll fix it.

**Comment by okankoese** [comment]
@mariusmotea 
OK I found the problem:
In ArduinoJson@6.9.1 the containsKey() function don't work, but it does in ArduinoJson@6.10.0 (which I was testing with).
However, there is a better way than using containsKey(), which I will implement the next days. I'll create a new pull request and delete this one :)

**Comment by okankoese** [comment]
@mariusmotea 
OK I found the problem:
In ArduinoJson@6.9.1 the containsKey() function don't work, but it does in ArduinoJson@6.10.0 (which I was testing with).
However, there is a better way than using containsKey(), which I will implement the next days.

**Comment by okanskose** [comment]
@mariusmotea 
OK I found the problem:
In ArduinoJson@6.9.1 the containsKey() function don't work, but it does in ArduinoJson@6.10.0 (which I was testing with).
However, there is a better way than using containsKey(), which I will implement the next days. I'll create a new pull request and delete this one.

**Comment by ghost** [comment]
@okankoese
Thanks for the info and supporting this project!

**Pull request closed without merging**
