### PR TITLE
Update Generic_WS2812_Strip.ino

### PR DESCRIPTION
**Pull request by Paalap**
Updating transition - there was an issue on remainig led after turning lights off one by one. (also some rework on transition logic overall)

### CODE REVIEW

**Comment by mariusmotea** [comment]
Hi,

Thanks for your work!  Did you test the changes of Generic_WS2812_Strip with 1, 2 and 3 segments to see if the transition leds behave normally in all 3 scenarios ?

**Comment by Paalap** [comment]
Yes, it is working well with all my test scenarios

**Comment by mariusmotea** [comment]
great!

**Comment by Burn-In** [comment]
Hi there, unfortunately the transision effect don't work very well within entertainment mode. Not only the unnecessary by 2 devider in blendingEntert(), which makes the transition LEDs darker, still exists. Also the whole transition sometimes don't work and there is no transition between lights. My code based on an old `WS2812BHueStrip.ino` and, after removing `/2`, the transition looks as expected.
[WS2812BHueStrip.zip](https://github.com/diyhue/Lights/files/12272929/WS2812BHueStrip.zip)

**Comment by Paalap** [comment]
Hi, not sure but in the updated code there is no blendingEnt more. And to be honest my focus was more on normal use, but entertainment test scenario worked fore also well

**Comment by Burn-In** [comment]
My apologies, it seems that I still was on a previous version. Your hint causes me to compare my used code again. Now I can confirm that everything works very well including the entertainment mode . No blending issues. Sorry and thanks for your work.

**Pull request merged**
