### PR TITLE
sync WS2812 changes & implement RGB to RGBW for SK6812

### LINKED ISSUE #127: Use SK6812 white LED for better color reproduction
Currently it seems like when hue or xy is used, white led is turned off (judging from the code alone), maybe we can use [this method](https://www.dmurph.com/posts/2021/1/cabinet-light-3.html) to convert RGB to RGBW to achieve better color reproduction?
Will try to implement this when my SK6812 arrive.

### PR DESCRIPTION
**Pull request by zhuoyang**
Initial implementation, need to hard code white color temperature RGB value, maybe make it configurable in the web interface?
Closes #127

### CODE REVIEW

**Comment by mariusmotea** [comment]
Thanks.

I think it will be complicated to add white balance in the web interface. I don't expect to have big differences from one vendor to another on leds color levels.

**Comment by zhuoyang** [comment]
The shop I bought my SK6812 has 3 variant for the white LED (warm, cool and natural), so I think it's good to have it configurable, but this is good enough for now.

**Comment by mariusmotea** [comment]
Only natural can be used i think. The white led is too powerful in order to be used if is not neutral white. I think we need a toggle switch to enable/disable the use of the white leds in combination with the color leds for the users who don't own the neutral white model can still get good colors without the white leds.

**Comment by zhuoyang** [comment]
There's a color correction implemented so it can be used for any white, but the RGB value of the white need to be configured according to the color temperature (https://andi-siess.de/rgb-to-color-temperature/)
For now it's hard coded to 3000K now because that's what I have. 

<blockquote><div><strong><a href="https://andi-siess.de/rgb-to-color-temperature/">RGB to color temperature – Andreas Siess</a></strong></div></blockquote>

**Comment by mariusmotea** [comment]
For the moment i think we can put in the header of the sketch the three options (warm white, cold white and neutral white) and have just the most common uncommented lines (i think neutral white is the most used). After that i will merge it and generate the firmware file for bin folder.

Thanks!

**Comment by mariusmotea** [comment]
Thanks for your contribution!

**Comment by Paalap** [comment]
@mariusmotea did you had any progress on this development?

**Pull request merged**
