### PR TITLE
ArduinoJson migration from version 5.13.4 to 6.10.0

### PR DESCRIPTION
**Pull request by okanskose**

### CODE REVIEW

**Comment by mariusmotea** [comment]
All looks good now. I will test on one of mi lights today.

**Comment by mariusmotea** [comment]
It is working. Thanks for entire work to this project.

**Comment by mariusmotea** [comment]
@cheesemarathon can you please check why the documentation is not re compiled after i made a commit in ReadTheDocs?

**Comment by ghost** [comment]
@marismotea Fixed, the webhook had screwed up somehow

**Pull request merged**
